FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3 \
    python3-pip \
    ssh \
    sshpass \
    git \
    apt-transport-https \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir ansible

# Create a user that will run Ansible
RUN useradd -m -s /bin/bash ansible

# Copy SSH keys and set permissions
COPY ssh-keys /home/ansible/.ssh

RUN chown -R ansible:ansible /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh && \
    chmod 600 /home/ansible/.ssh/id_rsa* && \
    chmod 644 /home/ansible/.ssh/id_rsa*.pub && \
    chmod 600 /home/ansible/.ssh/authorized_keys

USER ansible
WORKDIR /home/ansible

CMD ["/bin/bash", "-c", "while sleep 3600; do :; done"]
