FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
software-properties-common \
python3 \
python3-pip \
ssh \
sshpass \
git \
apt-transport-https \
ca-certificates \
&& rm -rf /var/lib/apt/lists/*


RUN pip3 install --no-cache-dir ansible


# Create a user that will run Ansible
RUN useradd -m -s /bin/bash ansible
USER ansible
WORKDIR /home/ansible


CMD ["/bin/bash", "-c", "while sleep 3600; do :; done"]